version: '3.8'

services:
    excel-hydrator:
        build:
            context: ./go/excel-hydrator
        ports:
            - "8081:8080"        # для отладки (не обязательно)
        volumes:
            - ./excel/templates:/app/templates:ro
            - ./excel/output:/app/output
        restart: unless-stopped
